version: "3.7"

services:
  scrmtldb:
    image: postgres
    # TODO set volume for retentive
    environment:
        POSTGRES_USER: meinUser
        POSTGRES_PASSWORD: MeinNeuesPassword
        POSTGRES_DB: bestDb
    networks:
      - appnetwork

  scrmtlbackend:
    image: docker.pkg.github.com/scrmtl/server/scrmtl-server:latest
    depends_on:
      - scrmtldb
    environment:
      POSTGRES_HOST: scrmtldb
      POSTGRES_USER: meinUser
      POSTGRES_PASSWORD: MeinNeuesPassword
      POSTGRES_DB: bestDb
      # 'BACKEND_ALLOWED_HOSTS' should be a single string of hosts with a space between each.
      BACKEND_ALLOWED_HOSTS: homeserver.local
      # Trailing slash is necessary
      OVERWRITEWEBROOT: /scrmtl/
    labels:
      # actived traefik routing
      - traefik.enable=true
      # Choose network
      - traefik.docker.network=extern
      # http config
      - traefik.http.routers.scrmtlbackend.rule=Host(`homeserver.local`) && PathPrefix(`/scrmtl`)
      - traefik.http.routers.scrmtlbackend.entrypoints=web
      - traefik.http.routers.scrmtlbackend.middlewares=ScrmtlbackendStripPrefix@file
      # https config
      - traefik.http.routers.scrmtlbackend.middlewares=HttpsRedirect@file
      - traefik.http.routers.scrmtlbackend-secured.entrypoints=websecure
      - traefik.http.routers.scrmtlbackend-secured.tls=true
      - traefik.http.routers.scrmtlbackend-secured.rule=Host(`homeserver.local`) && PathPrefix(`/scrmtl`)
      - traefik.http.routers.scrmtlbackend-secured.middlewares=ScrmtlbackendMiddlewares@file
    networks:
      - appnetwork
      - extern

networks:
  extern:
    external: true
    driver: bridge
  appnetwork:
    external: false
    driver: bridge