api:
    dashboard: true
    insecure: false

log:
    level: "ERROR"
    # path to log files (NotChange)
    filePath: "/etc/traefik/loggingErrors.log"
    format: "json"

entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"

providers:
    docker:
        watch: true
        exposedbydefault: false
    file:
        # path to dynamic files (NotChange)
        filename: "/etc/traefik/dynamic-conf.yml"
        # autom. update
        watch: true
        
certificatesResolvers:
    myresolver:    
        acme:
            email: arminius4@hotmail.de
            storage: acme.json
            httpChallenge:
                # used during the challenge
                entryPoint: web
          
    