name: build and test frontend for NEXT
on:
  push:
    branches:
      - next
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    # Steps to deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        
    - name: Build
      # Run a multi-line script|
      run: |
        npm install
    - name: 'Run Jest'
      uses: stefanoeb/jest-action@1.0.3
      with:
        # Args to jest
        jestArgs: frontend/tests/unit/example.spec.js   
    - name: 'Unit Test'
      run: |
        npm install --progress=false
        npm run test:unit
  

      
